### PR TITLE
Enabled more tests in test/misc.

### PR DESCRIPTION
**Pull request by girish946**
Enabled following tests in test/misc.

* coro_traceback.lua
* coro_yield.lua
* debug_gc.lua
* dualnum.lua
* for_dir.lua
* hook_top.lua
* index
* jit_flush.lua
* loop_unroll.lua
* parse_comp.lua
* parse_esc.lua
* parse_misc.lua
* phi_conv.lua
* recurse_deep.lua
* recurse_tail.lua
* stack_gc.lua
* stack_purge.lua
* stackov.lua
* stackovc.lua
* tcall_base.lua
* tcall_loop.lua
* tonumber_scan.lua
* uclo.lua
* unordered_jit.lua
* wbarrier.lua
* wbarrier_jit.lua
* wbarrier_obar.lua

Signed-off-by: Girish Joshi <girish946@gmail.com>

### CODE REVIEW

**Comment by siddhesh** [comment]
Thanks, have you also tested these on the v2.1 branch?

**Comment by siddhesh** [comment]
Also, I'm looking at the CI results and the enabled tests don't seem to be running.  Can you please look into the logs and verify?

**Comment by girish946** [comment]
> Thanks, have you also tested these on the v2.1 branch?

On branch v2.1 two tests that are failing are `misc/gc_trace.lua` and `misc/hook_norecord.lua` on which I'm already working. The the tests that are enabled in the above commit are working on branch v2.1.


> Also, I'm looking at the CI results and the enabled tests don't seem to be running. Can you please look into the logs and verify?

I by mistake wrote `index` in the list above, which is not a test.
I have looked into logs rest of the tests are running.
Please let me know if I'm missing something.

Thanks.

**Comment by siddhesh** [comment]
Indeed, I think I saw the NOJIT output and concluded that they're not enabled.  Merged, thanks!

**Pull request merged**
